{
    "openapi": "3.0.2",
    "info": {
        "title": "BasketballCompetitions-API",
        "version": "1.0.0",
        "description": "### This is a Swagger UI for our Games API"
    },
    "paths": {
        "/games": {
            "summary": "Creates a game",
            "description": "Creates a new game",
            "get": {
                "tags": [
                    "games"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "List of games": {
                                        "value": [
                                            {
                                                "id": 1,
                                                "name": "Paide Cup"
                                            },
                                            {
                                                "id": 2,
                                                "name": "Veteranide Loivamine"
                                            }
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Returns a list of game names"
                    }
                },
                "summary": "Get a list of all game names",
                "description": "Returns a list of all game names in API"
            },
            "post": {
                "requestBody": {
                    "description": "A new game to be created",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/game-post"
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "games"
                ],
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/game-post"
                                },
                                "examples": {
                                    "new-game": {
                                        "value": {
                                            "id": "1",
                                            "name": "Tallinna cup",
                                            "location": "Lauluv√§ljak",
                                            "teamOneScore": 47,
                                            "teamTwoScore": 39,
                                            "teamOneId": 32,
                                            "teamTwoId": 29
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Game was added"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Invalid data": {
                                        "value": {
                                            "error": [
                                                "game.name cannot be null",
                                                "game.teamOneId cannot be null",
                                                "game.teamTwoId cannot be null"
                                            ]
                                        }
                                    }
                                }
                            }
                        },
                        "description": "One or all params are missing"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Internal Server Error": {
                                        "value": {
                                            "error": "Something went wrong on our side. Sorry :("
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Add new game",
                "description": "Add new game with all the details"
            }
        },
        "/players": {
            "get": {
                "tags": [
                    "players"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "List of players": {
                                        "value": [
                                            {
                                                "id": 1,
                                                "firstName": "Dagne Markiine",
                                                "lastName": "Kotkas"
                                            },
                                            {
                                                "id": 2,
                                                "firstName": "Andre",
                                                "lastName": "Luige"
                                            }
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Returns a list of player names"
                    }
                },
                "summary": "Get a list of all player names",
                "description": "Returns a list of all player names in API"
            },
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/player"
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "players"
                ],
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/player"
                                },
                                "examples": {
                                    "new-player": {
                                        "value": {
                                            "id": 3,
                                            "firstName": "Uku",
                                            "lastName": "Suviste",
                                            "age": 40
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Player was added"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Invalid data": {
                                        "value": {
                                            "error": [
                                                "player.firstName cannot be null",
                                                "player.lastName cannot be null",
                                                "player.age cannot be null"
                                            ]
                                        }
                                    }
                                }
                            }
                        },
                        "description": "One or all params are missing"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Internal Server Error": {
                                        "value": {
                                            "error": "Something went wrong on our side. Sorry :("
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Add new player",
                "description": "Add new player with all the details"
            }
        },
        "/teams": {
            "description": "",
            "get": {
                "tags": [
                    "teams"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "List of teams": {
                                        "value": [
                                            {
                                                "id": 1,
                                                "name": "Saaremaa Dunkers"
                                            },
                                            {
                                                "id": 2,
                                                "name": "T√µrva Sopsutajad"
                                            }
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Returns a list of team names"
                    }
                },
                "summary": "Get a list of all team names",
                "description": "Returns a list of all team names in API"
            },
            "post": {
                "requestBody": {
                    "description": "A new team to be created",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/team"
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "teams"
                ],
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/team"
                                },
                                "examples": {
                                    "new-team": {
                                        "value": {
                                            "id": 3,
                                            "name": "Vanalinna M√ºrajad",
                                            "homeCourt": "Metsas"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Team was added"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Invalid data": {
                                        "value": {
                                            "error": [
                                                "team.name cannot be null",
                                                "team.homeCourt cannot be null"
                                            ]
                                        }
                                    }
                                }
                            }
                        },
                        "description": "One or all params are missing"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Internal Server Error": {
                                        "value": {
                                            "error": "Something went wrong on our side. Sorry :("
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Add new team",
                "description": "Add new team with all the details"
            }
        },
        "/games/{id}": {
            "summary": "Get game details",
            "description": "Get all the details of a game with the given id",
            "get": {
                "tags": [
                    "games"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Full details of a given game": {
                                        "value": {
                                            "id": 1,
                                            "name": "Paide Cup",
                                            "location": "Paide",
                                            "teamOneName": "T√µrva Sopsutajad",
                                            "teamTwoName": "Saaremaa Dunkers",
                                            "teamOneScore": 67,
                                            "teamTwoScore": 85
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Returns full details of a given id game"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Game was not found": {
                                        "value": {
                                            "error": "Game not found"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Game was not found in games array"
                    }
                },
                "deprecated": false,
                "operationId": "gameId",
                "summary": "Get full details of a game",
                "description": "Returns full details of a given id game"
            },
            "put": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/game-post"
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "games"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/game-post"
                                },
                                "examples": {
                                    "Game was updated": {
                                        "value": {
                                            "name": "Tallinna cup",
                                            "location": "Lauluv√§ljak",
                                            "teamOneScore": 41,
                                            "teamTwoScore": 85,
                                            "teamOneId": 83,
                                            "teamTwoId": 97
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Game with given id was updated"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Game was not found\t": {
                                        "value": {
                                            "error": "Game not found"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Game with given id was not found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Internal Server Error": {
                                        "value": {
                                            "error": "Something went wrong on our side. Sorry :("
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Update game",
                "description": "Update game with given id"
            },
            "delete": {
                "tags": [
                    "games"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Game with given id was deleted"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Game was not found": {
                                        "value": {
                                            "error": "Game not found"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Game with given id was not found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Internal Server Error": {
                                        "value": {
                                            "error": "Something went wrong on our side. Sorry :("
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Delete game",
                "description": "Delete game with given id"
            },
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "required": true
                }
            ]
        },
        "/players/{id}": {
            "summary": "Get player details",
            "description": "Get all the details of a player with the given id",
            "get": {
                "tags": [
                    "players"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Full details of a given player": {
                                        "value": {
                                            "id": 1,
                                            "firstName": "Dagne Markiine",
                                            "lastName": "Kotkas",
                                            "age": 26
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Returns full details of a given id player"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Player was not found": {
                                        "value": {
                                            "error": "Player not found"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Player was not found in games array"
                    }
                },
                "deprecated": false,
                "operationId": "playerId",
                "summary": "Get full details of a player",
                "description": "Returns full details of a given id player"
            },
            "put": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/player"
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "players"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/player"
                                },
                                "examples": {
                                    "Player was updated": {
                                        "value": {
                                            "id": 3,
                                            "firstName": "Uku",
                                            "lastName": "Suviste",
                                            "age": 40
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Player with given id was updated"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Player was not found": {
                                        "value": {
                                            "error": "Player not found"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Player with given id was not found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Internal Server Error": {
                                        "value": {
                                            "error": "Something went wrong on our side. Sorry :("
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Update player",
                "description": "Update player with given id"
            },
            "delete": {
                "tags": [
                    "players"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Player with given id was deleted"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Player was not found": {
                                        "value": {
                                            "error": "Player not found"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Player with given id was not found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Internal Server Error": {
                                        "value": {
                                            "error": "Something went wrong on our side. Sorry :("
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Delete player",
                "description": "Delete player with given id"
            },
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "required": true
                }
            ]
        },
        "/teams/{id}": {
            "summary": "Get team details",
            "description": "Get all the details of a team with the given id",
            "get": {
                "tags": [
                    "teams"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Full details of a given team": {
                                        "value": {
                                            "id": 1,
                                            "name": "Saaremaa Dunkers",
                                            "homeCourt": "Kuressaare saal"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Returns full details of a given id team"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Team was not found": {
                                        "value": {
                                            "error": "Team not found"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Team was not found in teams array"
                    }
                },
                "deprecated": false,
                "operationId": "teamId",
                "summary": "Get full details of a team",
                "description": "Returns full details of a given id team"
            },
            "put": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/team"
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "teams"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/team"
                                },
                                "examples": {
                                    "Team was updated": {
                                        "value": {
                                            "id": 3,
                                            "name": "Vanalinna M√ºrajad",
                                            "homeCourt": "Metsas"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Team with given id was updated"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Team was not found": {
                                        "value": {
                                            "error": "Team not found"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Team with given id was not found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Internal Server Error": {
                                        "value": {
                                            "error": "Something went wrong on our side. Sorry :("
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Update team",
                "description": "Update team with given id"
            },
            "delete": {
                "tags": [
                    "teams"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Team with given id was deleted"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Team was not found": {
                                        "value": {
                                            "error": "Team not found"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Team with given id was not found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Internal Server Error": {
                                        "value": {
                                            "error": "Something went wrong on our side. Sorry :("
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Delete team",
                "description": "Delete team with given id"
            },
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "required": true
                }
            ]
        }
    },
    "components": {
        "schemas": {
            "error": {
                "title": "Root Type for error",
                "description": "",
                "type": "object",
                "properties": {
                    "error": {
                        "type": "string"
                    }
                },
                "example": {
                    "error": "Error message."
                }
            },
            "delete": {
                "title": "Root Type for delete",
                "description": "",
                "type": "object",
                "properties": {
                    "id": {
                        "format": "int32",
                        "type": "integer"
                    }
                },
                "example": {
                    "id": 1
                }
            },
            "player": {
                "title": "Root Type for player",
                "description": "",
                "required": [
                    "age",
                    "firstName",
                    "lastName"
                ],
                "type": "object",
                "properties": {
                    "firstName": {
                        "type": "string"
                    },
                    "lastName": {
                        "type": "string"
                    },
                    "age": {
                        "format": "int32",
                        "type": "integer"
                    }
                },
                "example": {
                    "firstName": "Uku",
                    "lastName": "Suviste",
                    "age": 40
                }
            },
            "team": {
                "title": "Root Type for team",
                "description": "",
                "required": [
                    "homeCourt",
                    "name"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "homeCourt": {
                        "type": "string"
                    }
                },
                "example": {
                    "name": "Vanalinna M√ºrajad",
                    "homeCourt": "Metsas"
                }
            },
            "game-post": {
                "title": "Root Type for game",
                "description": "",
                "required": [
                    "name",
                    "teamOneId",
                    "teamTwoId"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "description": "",
                        "type": "string"
                    },
                    "location": {
                        "description": "",
                        "type": "string"
                    },
                    "teamOneScore": {
                        "description": "",
                        "type": "integer"
                    },
                    "teamTwoScore": {
                        "description": "",
                        "type": "integer"
                    },
                    "teamOneId": {
                        "description": "",
                        "type": "integer"
                    },
                    "teamTwoId": {
                        "description": "",
                        "type": "integer"
                    }
                },
                "example": {
                    "name": "Tallinna Cup",
                    "location": "Lauluv√§ljak",
                    "teamOneId": 1,
                    "teamTwoId": 2,
                    "teamOneScore": 66,
                    "teamTwoScore": 99
                }
            },
            "game-get": {
                "title": "Root Type for game",
                "description": "",
                "required": [
                    "name",
                    "teamOneName",
                    "teamTwoName"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "description": "",
                        "type": "string"
                    },
                    "location": {
                        "description": "",
                        "type": "string"
                    },
                    "teamOneScore": {
                        "description": "",
                        "type": "integer"
                    },
                    "teamTwoScore": {
                        "description": "",
                        "type": "integer"
                    },
                    "teamOneName": {
                        "description": "",
                        "type": "string"
                    },
                    "teamTwoName": {
                        "description": "",
                        "type": "string"
                    }
                },
                "example": {
                    "name": "Tallinna Cup",
                    "location": "Lauluv√§ljak",
                    "teamOneName": "Sprinterid",
                    "teamTwoName": "Saaremaa sopsutajad",
                    "teamOneScore": 66,
                    "teamTwoScore": 99
                }
            }
        }
    }
}
